// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function Cancel(arg1:number):Promise<void>;

export function ChooseDownloadDir():Promise<string>;

export function Download(arg1:number,arg2:string,arg3:string):Promise<void>;

export function GetConfig():Promise<main.UIConfig>;

export function ListIssues():Promise<Array<main.IssueVM>>;

export function Login(arg1:string,arg2:string,arg3:boolean):Promise<string>;

export function OpenDownloadDir():Promise<void>;

export function OpenFile(arg1:string):Promise<void>;
